/**
 * A list of common companies mentioned on WSB
 * @type {string[] : {ticker: string, name: string}}
 * @example
 * [
 *  {ticker: "GME", name: "GameStop"},
 * 
 */

const commonCompanies = [
  { ticker: "GME", name: "GameStop" },
  { ticker: "rdfn", name: "Redfin" },
  { ticker: "AMC", name: "AMC Entertainment" },
  { ticker: "BB", name: "BlackBerry" },
  { ticker: "PLTR", name: "Palantir" },
  { ticker: "TSLA", name: "Tesla" },
  { ticker: "NVDA", name: "Nvidia" },
  { ticker: "AAPL", name: "Apple" },
  { ticker: "MSFT", name: "Microsoft" },
  { ticker: "SPY", name: "S&P 500" },
  { ticker: "NOK", name: "Nokia" },
  { ticker: "TLRY", name: "Tilray" },
  { ticker: "AMZN", name: "Amazon" },
  { ticker: "AMD", name: "AMD" },
  { ticker: "NVDA", name: "Nvidia" },
  { ticker: "FB", name: "Facebook" },
  { ticker: "SNAP", name: "Snap" },
  { ticker: "TWTR", name: "Twitter" },
  { ticker: "GOOGL", name: "Google" },
  { ticker: "GOOG", name: "Google" },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "JPM", name: "JPMorgan Chase" },
  { ticker: "GS", name: "Goldman Sachs" },
  { ticker: "C", name: "Citigroup" },
  { ticker: "BAC", name: "Bank of America" },
  { ticker: "WFC", name: "Wells Fargo" },
  { ticker: "RKT", name: "Rocket Companies" },
  { ticker: "F", name: "Ford" },
  { ticker: "GM", name: "General Motors" },
  { ticker: "NIO", name: "NIO" },
  { ticker: "XPEV", name: "XPeng" },
  { ticker: "LI", name: "Li Auto" },
  { ticker: "CCIV", name: "Churchill Capital" },
  { ticker: "SPCE", name: "Virgin Galactic" },
  { ticker: "DKNG", name: "DraftKings" },
  { ticker: "CLOV", name: "Clover Health" },
  { ticker: "PLUG", name: "Plug Power" },
  { ticker: "WKHS", name: "Workhorse" },
  { ticker: "RIDE", name: "Lordstown Motors" },
  { ticker: "QS", name: "QuantumScape" },
  { ticker: "FUBO", name: "fuboTV" },
  { ticker: "ROKU", name: "Roku" },
  { ticker: "PYPL", name: "PayPal" },
  { ticker: "SQ", name: "Square" },
  { ticker: "ZM", name: "Zoom" },
  { ticker: "UBER", name: "Uber" },
  { ticker: "LYFT", name: "Lyft" },
  { ticker: "PINS", name: "Pinterest" },
  { ticker: "SNOW", name: "Snowflake" },
  { ticker: "CRM", name: "Salesforce" },
  { ticker: "NET", name: "Cloudflare" },
  { ticker: "DOCU", name: "DocuSign" },
  { ticker: "SHOP", name: "Shopify" },
  { ticker: "SE", name: "Sea Limited" },
  { ticker: "BABA", name: "Alibaba" },
  { ticker: "JD", name: "JD.com" },
  { ticker: "TCEHY", name: "Tencent" },
  { ticker: "BIDU", name: "Baidu" },
  { ticker: "NIO", name: "NIO" },
  { ticker: "XPEV", name: "XPeng" },
  { ticker: "LI", name: "Li Auto" },
  { ticker: "CCIV", name: "Churchill Capital" },
  { ticker: "SPCE", name: "Virgin Galactic" },
  { ticker: "DKNG", name: "DraftKings" },
  { ticker: "CLOV", name: "Clover Health" },
  { ticker: "PLUG", name: "Plug Power" },
  { ticker: "WKHS", name: "Workhorse" },
  { ticker: "RIDE", name: "Lordstown Motors" },
  { ticker: "QS", name: "QuantumScape" },
  { ticker: "LCID", name: "Lucid Motors" },
  { ticker: "LMT", name: "Lockheed Martin" },
  { ticker: "RTX", name: "Raytheon Technologies" },
]

export default commonCompanies